import type { NextApiRequest, NextPage } from "next";
import Head from 'next/head';
import { prisma } from "~/server/db";

export async function getServerSideProps(req: NextApiRequest){
  const id = req.query.id;
  const url = await prisma.url.findUnique({
    where: {
      slug: id as string
    }
  })

  if (url) {
    return {
      redirect: {
        destination: url.url,
        permanent: false,
      },
    };
  } else {
    return {
      notFound: true,
    };
  }
}

const HashPage: NextPage = () => {
  return (
    <div>
      <Head>
        <title>URL Shortener</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Requested link not found</h1>
    </div>
  );
};

export default HashPage;